### ISSUE TITLE
Bug with case_sensitive = false

### ISSUE THREAD

**Issue by pablomg92z** [OpsLevel/terraform-provider-opslevel#179] opened 2024-01-03 08:56 UTC
Since version "0.8.13" there is a problem when after adding case_sensitive = false in a predicate of a filter as seen below, the changes are never applied after running terraform apply even though they are reported as successfully applied.

```
resource "opslevel_filter" "language_services" {
  name = "service_name"
  predicate {
    case_sensitive = false
    key            = "language"
    type           = "contains"
    value          = "something"
  }
}
```

So it looks like it only allows case_sensitive = true.

I saw a new version 0.8.14 is out and we tried that but the issue still remains the same. Could you have a look into it? Thanks!

**Comment by taimoorgit** [comment] 2024-01-03 17:48
@pablomg92z thanks a lot for reporting this bug and providing the steps to reproduce it! 😃 

This is happening because our [Terraform provider version cannot differentiate between unset and zero values](https://github.com/hashicorp/terraform/issues/25872). To get around this, we are marking all boolean fields as `Required`. This will require you to update your configuration files to set all boolean values explicitly, but it's the cleanest solution we can make right now without rewriting the entire provider to use the new Terraform SDK.

This has now been fixed in https://github.com/OpsLevel/terraform-provider-opslevel/pull/180 and our next release will include that change. Our next release is expected Friday, Jan 5th 2024.

**Closed by taimoorgit** 2024-01-03 17:48 UTC
